# Generated by Django 3.2.12 on 2022-02-21 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='images/profilePic.png', upload_to='profile/%Y/%m/%d/')),
                ('background_pic', models.ImageField(default='images/backgroundPic.jpg', upload_to='background/%Y/%m/%d/')),
                ('block_users', models.ManyToManyField(blank=True, related_name='blockUsers', to=settings.AUTH_USER_MODEL)),
                ('blocked_by_users', models.ManyToManyField(blank=True, related_name='blockByUsers', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
