# Generated by Django 3.2.12 on 2022-03-02 19:49

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=600)),
                ('category', models.CharField(choices=[('world', 'World'), ('environment', 'Environment'), ('technology', 'Technology'), ('design', 'Design'), ('culture', 'Culture'), ('business', 'Business'), ('politics', 'Politics'), ('opinion', 'Opinion'), ('science', 'Science'), ('health', 'Health'), ('style', 'Style'), ('travel', 'Travel')], default='world', max_length=50)),
                ('description', models.TextField()),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('thumbnail', models.ImageField(blank=True, default='images/thumbnail.jpeg', null=True, upload_to='thumbnail/%Y/%m/%d/')),
                ('like', models.ManyToManyField(blank=True, related_name='likes', to='accounts.Blogger')),
                ('shares', models.ManyToManyField(blank=True, related_name='shares', to='accounts.Blogger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='accounts.blogger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog')),
                ('like', models.ManyToManyField(related_name='sbLikes', to='accounts.Blogger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.blogger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('text', models.TextField()),
                ('slug', models.SlugField(max_length=500)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('like', models.ManyToManyField(blank=True, related_name='cLikes', to='accounts.Blogger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.blogger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
