# Generated by Django 3.2.12 on 2022-03-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='slug',
            field=models.SlugField(max_length=500, null=True),
        ),
    ]
